### ISSUE TITLE
Incorrect eu vat reporting

### ISSUE THREAD

**Issue by shawaj** [baselbers/woocommerce-pdf-invoices#188]
When a customer has ordered from USA, which would be zero rated because it is outside of the EU, a line gets put on the invoice saying:

"Zero rated for VAT as customer has supplied EU VAT number"

Obviously this is wrong - the reason it is zero rated in this instance would be because we are shipping to outside of the EU?

Thanks

**Comment by baselbers** [comment]
This should have been fixed in latest version. Are you using 2.9.1?
https://github.com/baselbers/woocommerce-pdf-invoices/commit/9dfcee7ea2c8b692eb16edafcdf78a6d6300949c

**Comment by shawaj** [comment]
Yes this is on version 2.9.1 so obviously it's not fixed yet...

**Comment by baselbers** [comment]
That is really strange because for orders outside EU '_vat_number_is_valid' can't be `true`. Can you debug this?

`'true' === $templater->get_meta( '_vat_number_is_valid' )`

**Comment by shawaj** [comment]
@baselbers

What would you like me to test?

**Comment by baselbers** [comment]
Try below and let me know what value you get.

<?php var_dump( $templater->get_meta( '_vat_number_is_valid' ) ); ?>

**Comment by shawaj** [comment]
Where should I try that?

**Comment by baselbers** [comment]
You could add it to one of the template files..

**Comment by shawaj** [comment]
@baselbers thanks very much, but could you tell me where in the template I should put it and what output I should expect and where?

**Comment by baselbers** [comment]
Just add it to header.php on last line, generate and invoice and send me a screenshot.

**Comment by baselbers** [comment]
@shawaj did you got any chance resolving this issue?

**Comment by shawaj** [comment]
@baselbers header.php of the theme or of your plugin?

**Comment by shawaj** [comment]
Anyway, after the latest update the plugin just does not work at all!

**Comment by baselbers** [comment]
@shawaj Would like to know if you have been able to resolve the problem. The [FAQ ](https://wordpress.org/plugins/woocommerce-pdf-invoices/)will explain how to add the VAT notice to the invoice.
